In [12]:
import pandas as pd
from deepeval.metrics import GEval
from deepeval.models import GPTModel
from deepeval.test_case import LLMTestCase, LLMTestCaseParams
from dotenv import load_dotenv
import warnings
import os

In [13]:
load_dotenv()

API_KEY = os.getenv('API_KEY')

In [14]:
warnings.filterwarnings('ignore')
os.environ["CONFIDENT_METRIC_LOGGING_VERBOSE"] = "0"

In [21]:
abstracts = pd.read_csv('/home/vinicius/Área de Trabalho/Artigos/llm_artigo/llmArtigo/datasets/Abstracts_ORA - abstracts.csv')

In [23]:
abstracts = abstracts.drop(['division', 'department'], axis=1)

In [24]:
abstracts

,title,abstract
0,Niu_2025_Functional_Nanolayer_Dielectrics,Negatively charged dielectric films have signi...
1,Brody_2025_Numerical_simulation_of,Hypersonic flight is an essential component of...
2,Ehrenfels_2025_The_epistemology_of,This thesis addresses the question ‘Under what...
3,Greenrod_2025_Temperature_as_a,Thermal change has a profound impact on specie...
4,Chao_2025_Synthetic_transmembrane_transporters,The thesis describes the design and synthesis ...
5,Gao_2025_Association_between_neuroticism,"BACKGROUND: Neuroticism, a personality trait r..."
6,Parkes_2025_Magnetically-activated_DNA_and,Nucleic acids serve as the fundamental buildin...
7,Taskesen_2025_Tuning_magnetism_and,This thesis reports the synthesis and characte...
8,Rad_2025_Police_Unionism,"In 2024, there were over 1,300 incidents of po..."
9,Zong_2025_Sustainable_removal_of,Conventional wastewater treatment often fails ...
10,Van_Zijl_2025_Modelling_the_mechanisms,Healthy cerebral blood flow (CBF) control is v...
11,Rhee_2025_Frazil_ice_crystal,"Frazil ice crystals are small, often disk-shap..."
12,Mangas_Araujo_2025_Micromechanical_modelling_of,Many soft materials consist of rubbery network...
13,Birkhoelzer_2025_Investigation_of_skeletal,"Despite advances in treatment, heart failure (..."
14,Optimising_CRISPR_sgRNA_delivery_strategies_fo...,Gene therapy for inherited retinal diseases (I...
15,Vacalis_2025_Classical_and_quantum,This thesis presents methods for producing and...
16,Rosen_2025_Exhibiting_wounds_difficult,Cora Diamond introduced the concept of a ‘diff...
17,Hartinger_2025_Reducing_respiratory_losses,Enhancing agricultural productivity remains cr...
18,Sassarini_2025_Frege_puzzles_in,Frege puzzles arise in opaque contexts—linguis...
19,Teng_2025_New_machine_identity,Machine-to-machine communication (M2M) refers ...
20,El-Machachi_2025_Investigating_amorphous_graphene,The atomic-level structure of amorphous solids...
21,Wong_2025_Synthesis_of_Novel,S(VI) based moieties exhibit promising pharmac...
22,Heath_2025_Optimising_implant_pegs,Cementless orthopaedic implants are commonly h...
23,Whitehead_2025_Structural_Studies_of,Influenza viruses cause an estimated 3-5 milli...
24,Johnson_2025_Exploring_the_role,Primary cilia are essential organelles in skel...
25,Liang_2025_The_effects_of,Connected speech processes (CSPs) refer to alt...
26,Wellalagodage_2025_An_analysis_of,The focus of this thesis is the estimation of ...
27,Senese_2025_Structure_of_many-body,This thesis investigates the dynamics of quant...
28,Zhou_2025_Moderators_and_mediators,Anxiety disorders are among the most common me...
29,Collingwood_2025_A_computational_model,The neural mechanism of action-selection is of...

In [25]:
df = pd.read_csv('/home/vinicius/Área de Trabalho/Artigos/llm_artigo/llmArtigo/datasets/teses1_prompt_fixo_reduzido.csv')
df.tail()

,title,gemma-3-4b-it,gemma-3-4b-it_response,gemma-3-4b-it_time,gemma-3-4b-it_n_tokens_in,gemma-3-4b-it_n_tokens_out,gemma-3-12b-it,gemma-3-12b-it_response,gemma-3-12b-it_time,gemma-3-12b-it_n_tokens_in,...,gpt-oss-120b,gpt-oss-120b_response,gpt-oss-120b_time,gpt-oss-120b_n_tokens_in,gpt-oss-120b_n_tokens_out,gpt-oss-20b,gpt-oss-20b_response,gpt-oss-20b_time,gpt-oss-20b_n_tokens_in,gpt-oss-20b_n_tokens_out
25,Liang_2025_The_effects_of,NaN,Here’s the first iteration of the PhD thesis a...,32.919435,76450.0,197.0,NaN,This research investigates the perceptual chal...,110.217091,76450.0,...,NaN,This dissertation investigates the persistent ...,40.643243,74181,1488,NaN,The present doctoral research addresses the pe...,26.538514,74181,1750
26,Wellalagodage_2025_An_analysis_of,NaN,Here's the first iteration of the PhD thesis a...,35.195420,83612.0,225.0,NaN,This thesis investigates novel approaches to n...,120.859204,83612.0,...,NaN,The accurate quantification of cardiac output ...,36.536560,80299,849,NaN,Computed cardiopulmonography (CCP) integrates ...,28.282435,80299,1632
27,Senese_2025_Structure_of_many-body,NaN,The impact of quantum entanglement on the dyna...,29.179406,77478.0,190.0,NaN,This thesis investigates the dynamical propert...,101.083898,77478.0,...,NaN,The thesis addresses the exponential complexit...,38.723544,76409,1244,NaN,Quantum many‑body dynamics governed by local H...,61.987183,76409,6382
28,Zhou_2025_Moderators_and_mediators,NaN,Here’s the first iteration of the PhD thesis a...,35.185588,100380.0,210.0,NaN,Childhood anxiety disorders are characterized ...,118.404364,100380.0,...,NaN,Child anxiety disorders affect up to one‑third...,52.345843,93857,1584,NaN,NaN,87.208315,93857,8192
29,Collingwood_2025_A_computational_model,NaN,Here's the first iteration of the PhD thesis a...,31.492604,84692.0,298.0,NaN,This research investigates the neural and comp...,101.087764,84692.0,...,NaN,"Habitual behavior, defined as stimulus‑respons...",44.262039,86271,1215,NaN,"Habits, defined as stimulus‑response (S‑R) ass...",27.846690,86271,1248

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 96 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   title                                             30 non-null     str
 1   gemma-3-4b-it                                     0 non-null      float64
 2   gemma-3-4b-it_response                            30 non-null     str
 3   gemma-3-4b-it_time                                30 non-null     float64
 4   gemma-3-4b-it_n_tokens_in                         30 non-null     float64
 5   gemma-3-4b-it_n_tokens_out                        30 non-null     float64
 6   gemma-3-12b-it                                    0 non-null      float64
 7   gemma-3-12b-it_response                           30 non-null     str
 8   gemma-3-12b-it_time                               30 non-null     float64
 9   gemma-3-12b-it_n_tokens_in                        30 non-null     float64
 10  gemma-3-12b-it_n_tokens_out                       30 non-null     float64
 11  gemma-3-27b-it                                    0 non-null      float64
 12  gemma-3-27b-it_response                           30 non-null     str
 13  gemma-3-27b-it_time                               30 non-null     float64
 14  gemma-3-27b-it_n_tokens_in                        30 non-null     float64
 15  gemma-3-27b-it_n_tokens_out                       30 non-null     float64
 16  llama-3.3-70B-Instruct                            0 non-null      float64
 17  llama-3.3-70B-Instruct_response                   30 non-null     str
 18  llama-3.3-70B-Instruct_time                       30 non-null     float64
 19  llama-3.3-70B-Instruct_n_tokens_in                30 non-null     float64
 20  llama-3.3-70B-Instruct_n_tokens_out               30 non-null     float64
 21  DeepSeek-R1-Distill-Llama-70B                     0 non-null      float64
 22  DeepSeek-R1-Distill-Llama-70B_response            29 non-null     str
 23  DeepSeek-R1-Distill-Llama-70B_time                30 non-null     float64
 24  DeepSeek-R1-Distill-Llama-70B_n_tokens_in         30 non-null     float64
 25  DeepSeek-R1-Distill-Llama-70B_n_tokens_out        30 non-null     float64
 26  DeepSeek-R1-Distill-Qwen-32B                      0 non-null      float64
 27  DeepSeek-R1-Distill-Qwen-32B_response             30 non-null     str
 28  DeepSeek-R1-Distill-Qwen-32B_time                 30 non-null     float64
 29  DeepSeek-R1-Distill-Qwen-32B_n_tokens_in          30 non-null     float64
 30  DeepSeek-R1-Distill-Qwen-32B_n_tokens_out         30 non-null     float64
 31  mistral-small-3.2-24B-Instruct-2506               0 non-null      float64
 32  mistral-small-3.2-24B-Instruct-2506_response      30 non-null     str
 33  mistral-small-3.2-24B-Instruct-2506_time          30 non-null     float64
 34  mistral-small-3.2-24B-Instruct-2506_n_tokens_in   30 non-null     float64
 35  mistral-small-3.2-24B-Instruct-2506_n_tokens_out  30 non-null     float64
 36  qwen/qwen3-30b-a3b-2507                           0 non-null      float64
 37  qwen/qwen3-30b-a3b-2507_response                  30 non-null     str
 38  qwen/qwen3-30b-a3b-2507_time                      30 non-null     float64
 39  qwen/qwen3-30b-a3b-2507_n_tokens_in               30 non-null     float64
 40  qwen/qwen3-30b-a3b-2507_n_tokens_out              30 non-null     float64
 41  meta-llama-3.1-8B-Instruct                        0 non-null      float64
 42  meta-llama-3.1-8B-Instruct_response               30 non-null     str
 43  meta-llama-3.1-8B-Instruct_time                   30 non-null     float64
 44  meta-llama-3.1-8B-Instruct_n_tokens_in            30 non-null     float64
 45  meta-llama-3.1-8B-Instruct_n_tokens_out           30 non-null     float64
 46  llama-3.2-1B-Instruct                             0 non-null      float64
 47  llama-3.2-1B-Instruct_response                    30 non-null     str
 48  llama-3.2-1B-Instruct_time                        30 non-null     float64
 49  llama-3.2-1B-Instruct_n_tokens_in                 30 non-null     float64
 50  llama-3.2-1B-Instruct_n_tokens_out                30 non-null     float64
 51  llama-3.2-3B-Instruct                             0 non-null      float64
 52  llama-3.2-3B-Instruct_response                    30 non-null     str
 53  llama-3.2-3B-Instruct_time                        30 non-null     float64
 54  llama-3.2-3B-Instruct_n_tokens_in                 30 non-null     float64
 55  llama-3.2-3B-Instruct_n_tokens_out                30 non-null     float64
 56  DeepSeek-R1-Distill-Llama-8B                      0 non-null      float64
 57  DeepSeek-R1-Distill-Llama-8B_response             30 non-null     str
 58  DeepSeek-R1-Distill-Llama-8B_time                 30 non-null     float64
 59  DeepSeek-R1-Distill-Llama-8B_n_tokens_in          30 non-null     float64
 60  DeepSeek-R1-Distill-Llama-8B_n_tokens_out         30 non-null     float64
 61  DeepSeek-R1-Distill-Qwen-1.5B                     0 non-null      float64
 62  DeepSeek-R1-Distill-Qwen-1.5B_response            30 non-null     str
 63  DeepSeek-R1-Distill-Qwen-1.5B_time                30 non-null     float64
 64  DeepSeek-R1-Distill-Qwen-1.5B_n_tokens_in         30 non-null     float64
 65  DeepSeek-R1-Distill-Qwen-1.5B_n_tokens_out        30 non-null     float64
 66  DeepSeek-R1-Distill-Qwen-7B                       0 non-null      float64
 67  DeepSeek-R1-Distill-Qwen-7B_response              30 non-null     str
 68  DeepSeek-R1-Distill-Qwen-7B_time                  30 non-null     float64
 69  DeepSeek-R1-Distill-Qwen-7B_n_tokens_in           30 non-null     float64
 70  DeepSeek-R1-Distill-Qwen-7B_n_tokens_out          30 non-null     float64
 71  DeepSeek-R1-Distill-Qwen-14B                      0 non-null      float64
 72  DeepSeek-R1-Distill-Qwen-14B_response             30 non-null     str
 73  DeepSeek-R1-Distill-Qwen-14B_time                 30 non-null     float64
 74  DeepSeek-R1-Distill-Qwen-14B_n_tokens_in          30 non-null     float64
 75  DeepSeek-R1-Distill-Qwen-14B_n_tokens_out         30 non-null     float64
 76  Phi-4-mini-instruct                               0 non-null      float64
 77  Phi-4-mini-instruct_response                      30 non-null     str
 78  Phi-4-mini-instruct_time                          30 non-null     float64
 79  Phi-4-mini-instruct_n_tokens_in                   30 non-null     float64
 80  Phi-4-mini-instruct_n_tokens_out                  30 non-null     float64
 81  qwen/qwen3-4b-2507                                0 non-null      float64
 82  qwen/qwen3-4b-2507_response                       30 non-null     str
 83  qwen/qwen3-4b-2507_time                           30 non-null     float64
 84  qwen/qwen3-4b-2507_n_tokens_in                    30 non-null     float64
 85  qwen/qwen3-4b-2507_n_tokens_out                   30 non-null     float64
 86  gpt-oss-120b                                      0 non-null      float64
 87  gpt-oss-120b_response                             30 non-null     str
 88  gpt-oss-120b_time                                 30 non-null     float64
 89  gpt-oss-120b_n_tokens_in                          30 non-null     int64
 90  gpt-oss-120b_n_tokens_out                         30 non-null     int64
 91  gpt-oss-20b                                       0 non-null      float64
 92  gpt-oss-20b_response                              28 non-null     str
 93  gpt-oss-20b_time                                  30 non-null     float64
 94  gpt-oss-20b_n_tokens_in                           30 non-null     int64
 95  gpt-oss-20b_n_tokens_out                          30 non-null     int64
dtypes: float64(72), int64(4), str(20)
memory usage: 22.6 KB

In [26]:
model = GPTModel(
    model = "gpt-5",
    temperature= 0,
    api_key= API_KEY
)

In [27]:
model_columns = [col for col in df.columns if col.endswith("_response")]
model_columns

['gemma-3-4b-it_response',
 'gemma-3-12b-it_response',
 'gemma-3-27b-it_response',
 'llama-3.3-70B-Instruct_response',
 'DeepSeek-R1-Distill-Llama-70B_response',
 'DeepSeek-R1-Distill-Qwen-32B_response',
 'mistral-small-3.2-24B-Instruct-2506_response',
 'qwen/qwen3-30b-a3b-2507_response',
 'meta-llama-3.1-8B-Instruct_response',
 'llama-3.2-1B-Instruct_response',
 'llama-3.2-3B-Instruct_response',
 'DeepSeek-R1-Distill-Llama-8B_response',
 'DeepSeek-R1-Distill-Qwen-1.5B_response',
 'DeepSeek-R1-Distill-Qwen-7B_response',
 'DeepSeek-R1-Distill-Qwen-14B_response',
 'Phi-4-mini-instruct_response',
 'qwen/qwen3-4b-2507_response',
 'gpt-oss-120b_response',
 'gpt-oss-20b_response']

In [28]:
metric = GEval(
    name="Abstract_Quality",
    model= model,
    evaluation_steps=[
        "Verify whether the generated abstract preserves the core scientific elements of the reference, including problem, objectives, methodology, results, and contributions.",
    
        "Assess semantic fidelity: check if the generated abstract accurately represents the meaning of the reference without introducing distortions or hallucinations.",
    
        "Check for missing critical information from the reference abstract and penalize significant omissions.",
    
        "Ensure the output follows the style of a scientific abstract, without bullet points, markdown formatting, reasoning traces, or meta-commentary.",
    
        "Evaluate conciseness: the abstract should be compact and avoid unnecessary verbosity or redundancy."
        ],
    evaluation_params=[
        LLMTestCaseParams.ACTUAL_OUTPUT,
        LLMTestCaseParams.EXPECTED_OUTPUT,
    ],

)

In [29]:
import pandas as pd
import os
from deepeval.test_case import LLMTestCase
from deepeval import evaluate

output_file = "geval_results_gpt.csv"

for idx in range(len(df)):
    title = df.loc[idx, "title"] if "title" in df.columns else f"thesis_{idx}"
    reference_abstract = abstracts.loc[idx, "abstract"]

    for model_col in model_columns:
        model_name = model_col.replace("_response", "")
        candidate_summary = df.loc[idx, model_col]

        # Pula inferências nulas ou vazias
        if pd.isna(candidate_summary) or str(candidate_summary).strip() == "":
            print(f"[SKIP] idx={idx} | model={model_name} → inferência vazia")
            result_row = {
                "idx":          idx,
                "title":        title,
                "model":        model_name,
                "geval_score":  None,
                "geval_reason": "skipped: empty inference"
            }
        else:
            try:
                test_case = LLMTestCase(
                    input=title,
                    actual_output=str(candidate_summary),
                    expected_output=str(reference_abstract)
                )
                metric.measure(test_case)
                result_row = {
                    "idx":          idx,
                    "title":        title,
                    "model":        model_name,
                    "geval_score":  metric.score,
                    "geval_reason": metric.reason
                }
                print(f"[OK] idx={idx} | model={model_name} | score={metric.score:.3f}")

            except Exception as e:
                print(f"[ERROR] idx={idx} | model={model_name} → {e}")
                result_row = {
                    "idx":          idx,
                    "title":        title,
                    "model":        model_name,
                    "geval_score":  None,
                    "geval_reason": f"error: {str(e)}"
                }

        # Salva incrementalmente — protege contra crashes
        temp_df = pd.DataFrame([result_row])
        if os.path.exists(output_file):
            temp_df.to_csv(output_file, mode="a", header=False, index=False)
        else:
            temp_df.to_csv(output_file, mode="w", header=True, index=False)

print(f"\n✅ Avaliação concluída! Resultados salvos em '{output_file}'")

[OK] idx=0 | model=gemma-3-4b-it | score=0.300

[OK] idx=0 | model=gemma-3-12b-it | score=0.500

[OK] idx=0 | model=gemma-3-27b-it | score=0.600

[OK] idx=0 | model=llama-3.3-70B-Instruct | score=0.400

[OK] idx=0 | model=DeepSeek-R1-Distill-Llama-70B | score=0.200

[OK] idx=0 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.500

[OK] idx=0 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.300

[OK] idx=0 | model=qwen/qwen3-30b-a3b-2507 | score=0.700

[OK] idx=0 | model=meta-llama-3.1-8B-Instruct | score=0.300

[OK] idx=0 | model=llama-3.2-1B-Instruct | score=0.000

[OK] idx=0 | model=llama-3.2-3B-Instruct | score=0.200

[OK] idx=0 | model=DeepSeek-R1-Distill-Llama-8B | score=0.300

[OK] idx=0 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=0 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=0 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.200

[OK] idx=0 | model=Phi-4-mini-instruct | score=0.100

[OK] idx=0 | model=qwen/qwen3-4b-2507 | score=0.500

[OK] idx=0 | model=gpt-oss-120b | score=0.800

[OK] idx=0 | model=gpt-oss-20b | score=0.700

[OK] idx=1 | model=gemma-3-4b-it | score=0.200

[OK] idx=1 | model=gemma-3-12b-it | score=0.600

[OK] idx=1 | model=gemma-3-27b-it | score=0.600

[OK] idx=1 | model=llama-3.3-70B-Instruct | score=0.400

[OK] idx=1 | model=DeepSeek-R1-Distill-Llama-70B | score=0.300

[OK] idx=1 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.300

[OK] idx=1 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.600

[OK] idx=1 | model=qwen/qwen3-30b-a3b-2507 | score=0.600

[OK] idx=1 | model=meta-llama-3.1-8B-Instruct | score=0.200

[OK] idx=1 | model=llama-3.2-1B-Instruct | score=0.000

[OK] idx=1 | model=llama-3.2-3B-Instruct | score=0.200

[OK] idx=1 | model=DeepSeek-R1-Distill-Llama-8B | score=0.300

[OK] idx=1 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=1 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=1 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.300

[OK] idx=1 | model=Phi-4-mini-instruct | score=0.500

[OK] idx=1 | model=qwen/qwen3-4b-2507 | score=0.500

[OK] idx=1 | model=gpt-oss-120b | score=0.700

[OK] idx=1 | model=gpt-oss-20b | score=0.800

[OK] idx=2 | model=gemma-3-4b-it | score=0.100

[OK] idx=2 | model=gemma-3-12b-it | score=0.300

[OK] idx=2 | model=gemma-3-27b-it | score=0.400

[OK] idx=2 | model=llama-3.3-70B-Instruct | score=0.300

[OK] idx=2 | model=DeepSeek-R1-Distill-Llama-70B | score=0.100

[OK] idx=2 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.300

[OK] idx=2 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.700

[OK] idx=2 | model=qwen/qwen3-30b-a3b-2507 | score=0.600

[OK] idx=2 | model=meta-llama-3.1-8B-Instruct | score=0.200

[OK] idx=2 | model=llama-3.2-1B-Instruct | score=0.200

[OK] idx=2 | model=llama-3.2-3B-Instruct | score=0.300

[OK] idx=2 | model=DeepSeek-R1-Distill-Llama-8B | score=0.100

[OK] idx=2 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=2 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=2 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.200

[OK] idx=2 | model=Phi-4-mini-instruct | score=0.300

[OK] idx=2 | model=qwen/qwen3-4b-2507 | score=0.400

[OK] idx=2 | model=gpt-oss-120b | score=0.400

[OK] idx=2 | model=gpt-oss-20b | score=0.400

[OK] idx=3 | model=gemma-3-4b-it | score=0.200

[OK] idx=3 | model=gemma-3-12b-it | score=0.600

[OK] idx=3 | model=gemma-3-27b-it | score=0.500

[OK] idx=3 | model=llama-3.3-70B-Instruct | score=0.600

[OK] idx=3 | model=DeepSeek-R1-Distill-Llama-70B | score=0.400

[OK] idx=3 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.400

[OK] idx=3 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.700

[OK] idx=3 | model=qwen/qwen3-30b-a3b-2507 | score=0.600

[OK] idx=3 | model=meta-llama-3.1-8B-Instruct | score=0.300

[OK] idx=3 | model=llama-3.2-1B-Instruct | score=0.200

[OK] idx=3 | model=llama-3.2-3B-Instruct | score=0.200

[OK] idx=3 | model=DeepSeek-R1-Distill-Llama-8B | score=0.200

[OK] idx=3 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=3 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=3 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.200

[OK] idx=3 | model=Phi-4-mini-instruct | score=0.300

[OK] idx=3 | model=qwen/qwen3-4b-2507 | score=0.800

[OK] idx=3 | model=gpt-oss-120b | score=0.700

[OK] idx=3 | model=gpt-oss-20b | score=0.700

[OK] idx=4 | model=gemma-3-4b-it | score=0.300

[OK] idx=4 | model=gemma-3-12b-it | score=0.700

[OK] idx=4 | model=gemma-3-27b-it | score=0.700

[OK] idx=4 | model=llama-3.3-70B-Instruct | score=0.600

[OK] idx=4 | model=DeepSeek-R1-Distill-Llama-70B | score=0.200

[OK] idx=4 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.300

[OK] idx=4 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.700

[OK] idx=4 | model=qwen/qwen3-30b-a3b-2507 | score=0.600

[OK] idx=4 | model=meta-llama-3.1-8B-Instruct | score=0.200

[OK] idx=4 | model=llama-3.2-1B-Instruct | score=0.000

[OK] idx=4 | model=llama-3.2-3B-Instruct | score=0.600

[OK] idx=4 | model=DeepSeek-R1-Distill-Llama-8B | score=0.200

[OK] idx=4 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=4 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.100

[OK] idx=4 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.300

[OK] idx=4 | model=Phi-4-mini-instruct | score=0.800

[OK] idx=4 | model=qwen/qwen3-4b-2507 | score=0.400

[OK] idx=4 | model=gpt-oss-120b | score=0.800

[OK] idx=4 | model=gpt-oss-20b | score=0.600

[OK] idx=5 | model=gemma-3-4b-it | score=0.400

[OK] idx=5 | model=gemma-3-12b-it | score=0.400

[OK] idx=5 | model=gemma-3-27b-it | score=0.600

[OK] idx=5 | model=llama-3.3-70B-Instruct | score=0.600

[OK] idx=5 | model=DeepSeek-R1-Distill-Llama-70B | score=0.300

[OK] idx=5 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.200

[OK] idx=5 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.400

[OK] idx=5 | model=qwen/qwen3-30b-a3b-2507 | score=0.700

[OK] idx=5 | model=meta-llama-3.1-8B-Instruct | score=0.300

[OK] idx=5 | model=llama-3.2-1B-Instruct | score=0.100

[OK] idx=5 | model=llama-3.2-3B-Instruct | score=0.200

[OK] idx=5 | model=DeepSeek-R1-Distill-Llama-8B | score=0.300

[OK] idx=5 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=5 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.100

[OK] idx=5 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.100

[OK] idx=5 | model=Phi-4-mini-instruct | score=0.400

[OK] idx=5 | model=qwen/qwen3-4b-2507 | score=0.500

[OK] idx=5 | model=gpt-oss-120b | score=0.800

[OK] idx=5 | model=gpt-oss-20b | score=0.700

[OK] idx=6 | model=gemma-3-4b-it | score=0.300

[OK] idx=6 | model=gemma-3-12b-it | score=0.500

[OK] idx=6 | model=gemma-3-27b-it | score=0.700

[OK] idx=6 | model=llama-3.3-70B-Instruct | score=0.600

[OK] idx=6 | model=DeepSeek-R1-Distill-Llama-70B | score=0.300

[OK] idx=6 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.400

[OK] idx=6 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.900

[OK] idx=6 | model=qwen/qwen3-30b-a3b-2507 | score=0.600

[OK] idx=6 | model=meta-llama-3.1-8B-Instruct | score=0.300

[OK] idx=6 | model=llama-3.2-1B-Instruct | score=0.100

[OK] idx=6 | model=llama-3.2-3B-Instruct | score=0.200

[OK] idx=6 | model=DeepSeek-R1-Distill-Llama-8B | score=0.300

[OK] idx=6 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=6 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=6 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.500

[OK] idx=6 | model=Phi-4-mini-instruct | score=0.200

[OK] idx=6 | model=qwen/qwen3-4b-2507 | score=0.700

[OK] idx=6 | model=gpt-oss-120b | score=0.900

[OK] idx=6 | model=gpt-oss-20b | score=0.800

[OK] idx=7 | model=gemma-3-4b-it | score=0.100

[OK] idx=7 | model=gemma-3-12b-it | score=0.300

[OK] idx=7 | model=gemma-3-27b-it | score=0.500

[OK] idx=7 | model=llama-3.3-70B-Instruct | score=0.500

[OK] idx=7 | model=DeepSeek-R1-Distill-Llama-70B | score=0.300

[OK] idx=7 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.300

[OK] idx=7 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.600

[OK] idx=7 | model=qwen/qwen3-30b-a3b-2507 | score=0.300

[OK] idx=7 | model=meta-llama-3.1-8B-Instruct | score=0.300

[OK] idx=7 | model=llama-3.2-1B-Instruct | score=0.000

[OK] idx=7 | model=llama-3.2-3B-Instruct | score=0.300

[OK] idx=7 | model=DeepSeek-R1-Distill-Llama-8B | score=0.300

[OK] idx=7 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=7 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=7 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.300

[OK] idx=7 | model=Phi-4-mini-instruct | score=0.200

[OK] idx=7 | model=qwen/qwen3-4b-2507 | score=0.300

[OK] idx=7 | model=gpt-oss-120b | score=0.900

[OK] idx=7 | model=gpt-oss-20b | score=0.300

[OK] idx=8 | model=gemma-3-4b-it | score=0.400

[OK] idx=8 | model=gemma-3-12b-it | score=0.500

[OK] idx=8 | model=gemma-3-27b-it | score=0.600

[OK] idx=8 | model=llama-3.3-70B-Instruct | score=0.600

[OK] idx=8 | model=DeepSeek-R1-Distill-Llama-70B | score=0.300

[OK] idx=8 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.300

[OK] idx=8 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.500

[OK] idx=8 | model=qwen/qwen3-30b-a3b-2507 | score=0.600

[OK] idx=8 | model=meta-llama-3.1-8B-Instruct | score=0.200

[OK] idx=8 | model=llama-3.2-1B-Instruct | score=0.000

[OK] idx=8 | model=llama-3.2-3B-Instruct | score=0.300

[OK] idx=8 | model=DeepSeek-R1-Distill-Llama-8B | score=0.300

[OK] idx=8 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=8 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=8 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.200

[OK] idx=8 | model=Phi-4-mini-instruct | score=0.400

[OK] idx=8 | model=qwen/qwen3-4b-2507 | score=0.500

[OK] idx=8 | model=gpt-oss-120b | score=0.400

[OK] idx=8 | model=gpt-oss-20b | score=0.300

[OK] idx=9 | model=gemma-3-4b-it | score=0.400

[OK] idx=9 | model=gemma-3-12b-it | score=0.500

[OK] idx=9 | model=gemma-3-27b-it | score=0.300

[OK] idx=9 | model=llama-3.3-70B-Instruct | score=0.600

[OK] idx=9 | model=DeepSeek-R1-Distill-Llama-70B | score=0.500

[OK] idx=9 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.300

[OK] idx=9 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.600

[OK] idx=9 | model=qwen/qwen3-30b-a3b-2507 | score=0.400

[OK] idx=9 | model=meta-llama-3.1-8B-Instruct | score=0.700

[OK] idx=9 | model=llama-3.2-1B-Instruct | score=0.100

[OK] idx=9 | model=llama-3.2-3B-Instruct | score=0.200

[OK] idx=9 | model=DeepSeek-R1-Distill-Llama-8B | score=0.300

[OK] idx=9 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=9 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=9 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.300

[OK] idx=9 | model=Phi-4-mini-instruct | score=0.000

[OK] idx=9 | model=qwen/qwen3-4b-2507 | score=0.400

[OK] idx=9 | model=gpt-oss-120b | score=0.700
[SKIP] idx=9 | model=gpt-oss-20b → inferência vazia

[OK] idx=10 | model=gemma-3-4b-it | score=0.300

[OK] idx=10 | model=gemma-3-12b-it | score=0.600

[OK] idx=10 | model=gemma-3-27b-it | score=0.600

[OK] idx=10 | model=llama-3.3-70B-Instruct | score=0.700

[OK] idx=10 | model=DeepSeek-R1-Distill-Llama-70B | score=0.300

[OK] idx=10 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.300

[OK] idx=10 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.300

[OK] idx=10 | model=qwen/qwen3-30b-a3b-2507 | score=0.700

[OK] idx=10 | model=meta-llama-3.1-8B-Instruct | score=0.600

[OK] idx=10 | model=llama-3.2-1B-Instruct | score=0.100

[OK] idx=10 | model=llama-3.2-3B-Instruct | score=0.200

[OK] idx=10 | model=DeepSeek-R1-Distill-Llama-8B | score=0.300

[OK] idx=10 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=10 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=10 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.300

[OK] idx=10 | model=Phi-4-mini-instruct | score=0.300

[OK] idx=10 | model=qwen/qwen3-4b-2507 | score=0.600

[OK] idx=10 | model=gpt-oss-120b | score=0.800

[OK] idx=10 | model=gpt-oss-20b | score=0.700

[OK] idx=11 | model=gemma-3-4b-it | score=0.200

[OK] idx=11 | model=gemma-3-12b-it | score=0.300

[OK] idx=11 | model=gemma-3-27b-it | score=0.500

[OK] idx=11 | model=llama-3.3-70B-Instruct | score=0.400
[SKIP] idx=11 | model=DeepSeek-R1-Distill-Llama-70B → inferência vazia

[OK] idx=11 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.200

[OK] idx=11 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.200

[OK] idx=11 | model=qwen/qwen3-30b-a3b-2507 | score=0.400

[OK] idx=11 | model=meta-llama-3.1-8B-Instruct | score=0.300

[OK] idx=11 | model=llama-3.2-1B-Instruct | score=0.200

[OK] idx=11 | model=llama-3.2-3B-Instruct | score=0.300

[OK] idx=11 | model=DeepSeek-R1-Distill-Llama-8B | score=0.000

[OK] idx=11 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=11 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=11 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.200

[OK] idx=11 | model=Phi-4-mini-instruct | score=0.000

[OK] idx=11 | model=qwen/qwen3-4b-2507 | score=0.400

[OK] idx=11 | model=gpt-oss-120b | score=0.500

[OK] idx=11 | model=gpt-oss-20b | score=0.300

[OK] idx=12 | model=gemma-3-4b-it | score=0.500

[OK] idx=12 | model=gemma-3-12b-it | score=0.400

[OK] idx=12 | model=gemma-3-27b-it | score=0.300

[OK] idx=12 | model=llama-3.3-70B-Instruct | score=0.300

[OK] idx=12 | model=DeepSeek-R1-Distill-Llama-70B | score=0.200

[OK] idx=12 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.300

[OK] idx=12 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.300

[OK] idx=12 | model=qwen/qwen3-30b-a3b-2507 | score=0.600

[OK] idx=12 | model=meta-llama-3.1-8B-Instruct | score=0.700

[OK] idx=12 | model=llama-3.2-1B-Instruct | score=0.000

[OK] idx=12 | model=llama-3.2-3B-Instruct | score=0.300

[OK] idx=12 | model=DeepSeek-R1-Distill-Llama-8B | score=0.300

[OK] idx=12 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=12 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=12 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.300

[OK] idx=12 | model=Phi-4-mini-instruct | score=0.300

[OK] idx=12 | model=qwen/qwen3-4b-2507 | score=0.600

[OK] idx=12 | model=gpt-oss-120b | score=0.700

[OK] idx=12 | model=gpt-oss-20b | score=0.600

[OK] idx=13 | model=gemma-3-4b-it | score=0.200

[OK] idx=13 | model=gemma-3-12b-it | score=0.200

[OK] idx=13 | model=gemma-3-27b-it | score=0.600

[OK] idx=13 | model=llama-3.3-70B-Instruct | score=0.300

[OK] idx=13 | model=DeepSeek-R1-Distill-Llama-70B | score=0.700

[OK] idx=13 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.300

[OK] idx=13 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.400

[OK] idx=13 | model=qwen/qwen3-30b-a3b-2507 | score=0.700

[OK] idx=13 | model=meta-llama-3.1-8B-Instruct | score=0.300

[OK] idx=13 | model=llama-3.2-1B-Instruct | score=0.200

[OK] idx=13 | model=llama-3.2-3B-Instruct | score=0.200

[OK] idx=13 | model=DeepSeek-R1-Distill-Llama-8B | score=0.300

[OK] idx=13 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=13 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=13 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.200

[OK] idx=13 | model=Phi-4-mini-instruct | score=0.300

[OK] idx=13 | model=qwen/qwen3-4b-2507 | score=0.400

[OK] idx=13 | model=gpt-oss-120b | score=0.800

[OK] idx=13 | model=gpt-oss-20b | score=0.600

[OK] idx=14 | model=gemma-3-4b-it | score=0.300

[OK] idx=14 | model=gemma-3-12b-it | score=0.400

[OK] idx=14 | model=gemma-3-27b-it | score=0.600

[OK] idx=14 | model=llama-3.3-70B-Instruct | score=0.400

[OK] idx=14 | model=DeepSeek-R1-Distill-Llama-70B | score=0.100

[OK] idx=14 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.200

[OK] idx=14 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.600

[OK] idx=14 | model=qwen/qwen3-30b-a3b-2507 | score=0.500

[OK] idx=14 | model=meta-llama-3.1-8B-Instruct | score=0.300

[OK] idx=14 | model=llama-3.2-1B-Instruct | score=0.100

[OK] idx=14 | model=llama-3.2-3B-Instruct | score=0.300

[OK] idx=14 | model=DeepSeek-R1-Distill-Llama-8B | score=0.100

[OK] idx=14 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=14 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.100

[OK] idx=14 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.200

[OK] idx=14 | model=Phi-4-mini-instruct | score=0.200

[OK] idx=14 | model=qwen/qwen3-4b-2507 | score=0.300

[OK] idx=14 | model=gpt-oss-120b | score=0.600

[OK] idx=14 | model=gpt-oss-20b | score=0.300

[OK] idx=15 | model=gemma-3-4b-it | score=0.000

[OK] idx=15 | model=gemma-3-12b-it | score=0.200

[OK] idx=15 | model=gemma-3-27b-it | score=0.300

[OK] idx=15 | model=llama-3.3-70B-Instruct | score=0.300

[OK] idx=15 | model=DeepSeek-R1-Distill-Llama-70B | score=0.200

[OK] idx=15 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.200

[OK] idx=15 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.800

[OK] idx=15 | model=qwen/qwen3-30b-a3b-2507 | score=0.600

[OK] idx=15 | model=meta-llama-3.1-8B-Instruct | score=0.500

[OK] idx=15 | model=llama-3.2-1B-Instruct | score=0.000

[OK] idx=15 | model=llama-3.2-3B-Instruct | score=0.200

[OK] idx=15 | model=DeepSeek-R1-Distill-Llama-8B | score=0.200

[OK] idx=15 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=15 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=15 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.200

[OK] idx=15 | model=Phi-4-mini-instruct | score=0.300

[OK] idx=15 | model=qwen/qwen3-4b-2507 | score=0.500

[OK] idx=15 | model=gpt-oss-120b | score=0.700

[OK] idx=15 | model=gpt-oss-20b | score=0.400

[OK] idx=16 | model=gemma-3-4b-it | score=0.300

[OK] idx=16 | model=gemma-3-12b-it | score=0.400

[OK] idx=16 | model=gemma-3-27b-it | score=0.400

[OK] idx=16 | model=llama-3.3-70B-Instruct | score=0.600

[OK] idx=16 | model=DeepSeek-R1-Distill-Llama-70B | score=0.100

[OK] idx=16 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.300

[OK] idx=16 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.500

[OK] idx=16 | model=qwen/qwen3-30b-a3b-2507 | score=0.800

[OK] idx=16 | model=meta-llama-3.1-8B-Instruct | score=0.700

[OK] idx=16 | model=llama-3.2-1B-Instruct | score=0.200

[OK] idx=16 | model=llama-3.2-3B-Instruct | score=0.300

[OK] idx=16 | model=DeepSeek-R1-Distill-Llama-8B | score=0.200

[OK] idx=16 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=16 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=16 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.200

[OK] idx=16 | model=Phi-4-mini-instruct | score=0.200

[OK] idx=16 | model=qwen/qwen3-4b-2507 | score=0.300

[OK] idx=16 | model=gpt-oss-120b | score=0.600

[OK] idx=16 | model=gpt-oss-20b | score=0.600

[OK] idx=17 | model=gemma-3-4b-it | score=0.300

[OK] idx=17 | model=gemma-3-12b-it | score=0.700

[OK] idx=17 | model=gemma-3-27b-it | score=0.700

[OK] idx=17 | model=llama-3.3-70B-Instruct | score=0.800

[OK] idx=17 | model=DeepSeek-R1-Distill-Llama-70B | score=0.400

[OK] idx=17 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.300

[OK] idx=17 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.700

[OK] idx=17 | model=qwen/qwen3-30b-a3b-2507 | score=0.600

[OK] idx=17 | model=meta-llama-3.1-8B-Instruct | score=0.300

[OK] idx=17 | model=llama-3.2-1B-Instruct | score=0.000

[OK] idx=17 | model=llama-3.2-3B-Instruct | score=0.600

[OK] idx=17 | model=DeepSeek-R1-Distill-Llama-8B | score=0.300

[OK] idx=17 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=17 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.100

[OK] idx=17 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.300

[OK] idx=17 | model=Phi-4-mini-instruct | score=0.300

[OK] idx=17 | model=qwen/qwen3-4b-2507 | score=0.600

[OK] idx=17 | model=gpt-oss-120b | score=0.700

[OK] idx=17 | model=gpt-oss-20b | score=0.600

[OK] idx=18 | model=gemma-3-4b-it | score=0.300

[OK] idx=18 | model=gemma-3-12b-it | score=0.600

[OK] idx=18 | model=gemma-3-27b-it | score=0.400

[OK] idx=18 | model=llama-3.3-70B-Instruct | score=0.300

[OK] idx=18 | model=DeepSeek-R1-Distill-Llama-70B | score=0.300

[OK] idx=18 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.300

[OK] idx=18 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.700

[OK] idx=18 | model=qwen/qwen3-30b-a3b-2507 | score=0.800

[OK] idx=18 | model=meta-llama-3.1-8B-Instruct | score=0.300

[OK] idx=18 | model=llama-3.2-1B-Instruct | score=0.000

[OK] idx=18 | model=llama-3.2-3B-Instruct | score=0.400

[OK] idx=18 | model=DeepSeek-R1-Distill-Llama-8B | score=0.200

[OK] idx=18 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=18 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=18 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.400

[OK] idx=18 | model=Phi-4-mini-instruct | score=0.400

[OK] idx=18 | model=qwen/qwen3-4b-2507 | score=0.400

[OK] idx=18 | model=gpt-oss-120b | score=0.600

[OK] idx=18 | model=gpt-oss-20b | score=0.400

[OK] idx=19 | model=gemma-3-4b-it | score=0.300

[OK] idx=19 | model=gemma-3-12b-it | score=0.400

[OK] idx=19 | model=gemma-3-27b-it | score=0.600

[OK] idx=19 | model=llama-3.3-70B-Instruct | score=0.600

[OK] idx=19 | model=DeepSeek-R1-Distill-Llama-70B | score=0.300

[OK] idx=19 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.200

[OK] idx=19 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.500

[OK] idx=19 | model=qwen/qwen3-30b-a3b-2507 | score=0.700

[OK] idx=19 | model=meta-llama-3.1-8B-Instruct | score=0.700

[OK] idx=19 | model=llama-3.2-1B-Instruct | score=0.100

[OK] idx=19 | model=llama-3.2-3B-Instruct | score=0.200

[OK] idx=19 | model=DeepSeek-R1-Distill-Llama-8B | score=0.300

[OK] idx=19 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=19 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=19 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.200

[OK] idx=19 | model=Phi-4-mini-instruct | score=0.600

[OK] idx=19 | model=qwen/qwen3-4b-2507 | score=0.700

[OK] idx=19 | model=gpt-oss-120b | score=0.700

[OK] idx=19 | model=gpt-oss-20b | score=0.600

[OK] idx=20 | model=gemma-3-4b-it | score=0.300

[OK] idx=20 | model=gemma-3-12b-it | score=0.400

[OK] idx=20 | model=gemma-3-27b-it | score=0.400

[OK] idx=20 | model=llama-3.3-70B-Instruct | score=0.600

[OK] idx=20 | model=DeepSeek-R1-Distill-Llama-70B | score=0.300

[OK] idx=20 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.300

[OK] idx=20 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.600

[OK] idx=20 | model=qwen/qwen3-30b-a3b-2507 | score=0.800

[OK] idx=20 | model=meta-llama-3.1-8B-Instruct | score=0.200

[OK] idx=20 | model=llama-3.2-1B-Instruct | score=0.200

[OK] idx=20 | model=llama-3.2-3B-Instruct | score=0.200

[OK] idx=20 | model=DeepSeek-R1-Distill-Llama-8B | score=0.200

[OK] idx=20 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=20 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=20 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.200

[OK] idx=20 | model=Phi-4-mini-instruct | score=0.400

[OK] idx=20 | model=qwen/qwen3-4b-2507 | score=0.500

[OK] idx=20 | model=gpt-oss-120b | score=0.800

[OK] idx=20 | model=gpt-oss-20b | score=0.500

[OK] idx=21 | model=gemma-3-4b-it | score=0.300

[OK] idx=21 | model=gemma-3-12b-it | score=0.400

[OK] idx=21 | model=gemma-3-27b-it | score=0.400

[OK] idx=21 | model=llama-3.3-70B-Instruct | score=0.600

[OK] idx=21 | model=DeepSeek-R1-Distill-Llama-70B | score=0.000

[OK] idx=21 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.100

[OK] idx=21 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.500

[OK] idx=21 | model=qwen/qwen3-30b-a3b-2507 | score=0.700

[OK] idx=21 | model=meta-llama-3.1-8B-Instruct | score=0.300

[OK] idx=21 | model=llama-3.2-1B-Instruct | score=0.100

[OK] idx=21 | model=llama-3.2-3B-Instruct | score=0.400

[OK] idx=21 | model=DeepSeek-R1-Distill-Llama-8B | score=0.200

[OK] idx=21 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=21 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=21 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.100

[OK] idx=21 | model=Phi-4-mini-instruct | score=0.500

[OK] idx=21 | model=qwen/qwen3-4b-2507 | score=0.300

[OK] idx=21 | model=gpt-oss-120b | score=0.700

[OK] idx=21 | model=gpt-oss-20b | score=0.200

[OK] idx=22 | model=gemma-3-4b-it | score=0.300

[OK] idx=22 | model=gemma-3-12b-it | score=0.400

[OK] idx=22 | model=gemma-3-27b-it | score=0.400

[OK] idx=22 | model=llama-3.3-70B-Instruct | score=0.500

[OK] idx=22 | model=DeepSeek-R1-Distill-Llama-70B | score=0.200

[OK] idx=22 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.200

[OK] idx=22 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.300

[OK] idx=22 | model=qwen/qwen3-30b-a3b-2507 | score=0.500

[OK] idx=22 | model=meta-llama-3.1-8B-Instruct | score=0.300

[OK] idx=22 | model=llama-3.2-1B-Instruct | score=0.000

[OK] idx=22 | model=llama-3.2-3B-Instruct | score=0.300

[OK] idx=22 | model=DeepSeek-R1-Distill-Llama-8B | score=0.200

[OK] idx=22 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=22 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=22 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.200

[OK] idx=22 | model=Phi-4-mini-instruct | score=0.300

[OK] idx=22 | model=qwen/qwen3-4b-2507 | score=0.400

[OK] idx=22 | model=gpt-oss-120b | score=0.600

[OK] idx=22 | model=gpt-oss-20b | score=0.300

[OK] idx=23 | model=gemma-3-4b-it | score=0.300

[OK] idx=23 | model=gemma-3-12b-it | score=0.300

[OK] idx=23 | model=gemma-3-27b-it | score=0.600

[OK] idx=23 | model=llama-3.3-70B-Instruct | score=0.700

[OK] idx=23 | model=DeepSeek-R1-Distill-Llama-70B | score=0.000

[OK] idx=23 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.200

[OK] idx=23 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.400

[OK] idx=23 | model=qwen/qwen3-30b-a3b-2507 | score=0.600

[OK] idx=23 | model=meta-llama-3.1-8B-Instruct | score=0.300

[OK] idx=23 | model=llama-3.2-1B-Instruct | score=0.100

[OK] idx=23 | model=llama-3.2-3B-Instruct | score=0.300

[OK] idx=23 | model=DeepSeek-R1-Distill-Llama-8B | score=0.000

[OK] idx=23 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=23 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.100

[OK] idx=23 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.200

[OK] idx=23 | model=Phi-4-mini-instruct | score=0.400

[OK] idx=23 | model=qwen/qwen3-4b-2507 | score=0.600

[OK] idx=23 | model=gpt-oss-120b | score=0.800

[OK] idx=23 | model=gpt-oss-20b | score=0.600

[OK] idx=24 | model=gemma-3-4b-it | score=0.300

[OK] idx=24 | model=gemma-3-12b-it | score=0.400

[OK] idx=24 | model=gemma-3-27b-it | score=0.400

[OK] idx=24 | model=llama-3.3-70B-Instruct | score=0.300

[OK] idx=24 | model=DeepSeek-R1-Distill-Llama-70B | score=0.100

[OK] idx=24 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.300

[OK] idx=24 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.400

[OK] idx=24 | model=qwen/qwen3-30b-a3b-2507 | score=0.300

[OK] idx=24 | model=meta-llama-3.1-8B-Instruct | score=0.200

[OK] idx=24 | model=llama-3.2-1B-Instruct | score=0.100

[OK] idx=24 | model=llama-3.2-3B-Instruct | score=0.200

[OK] idx=24 | model=DeepSeek-R1-Distill-Llama-8B | score=0.200

[OK] idx=24 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=24 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=24 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.100

[OK] idx=24 | model=Phi-4-mini-instruct | score=0.300

[OK] idx=24 | model=qwen/qwen3-4b-2507 | score=0.300

[OK] idx=24 | model=gpt-oss-120b | score=0.700

[OK] idx=24 | model=gpt-oss-20b | score=0.400

[OK] idx=25 | model=gemma-3-4b-it | score=0.300

[OK] idx=25 | model=gemma-3-12b-it | score=0.500

[OK] idx=25 | model=gemma-3-27b-it | score=0.700

[OK] idx=25 | model=llama-3.3-70B-Instruct | score=0.700

[OK] idx=25 | model=DeepSeek-R1-Distill-Llama-70B | score=0.400

[OK] idx=25 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.400

[OK] idx=25 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.500

[OK] idx=25 | model=qwen/qwen3-30b-a3b-2507 | score=0.600

[OK] idx=25 | model=meta-llama-3.1-8B-Instruct | score=0.300

[OK] idx=25 | model=llama-3.2-1B-Instruct | score=0.300

[OK] idx=25 | model=llama-3.2-3B-Instruct | score=0.500

[OK] idx=25 | model=DeepSeek-R1-Distill-Llama-8B | score=0.200

[OK] idx=25 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=25 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=25 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.300

[OK] idx=25 | model=Phi-4-mini-instruct | score=0.400

[OK] idx=25 | model=qwen/qwen3-4b-2507 | score=0.400

[OK] idx=25 | model=gpt-oss-120b | score=0.700

[OK] idx=25 | model=gpt-oss-20b | score=0.700

[OK] idx=26 | model=gemma-3-4b-it | score=0.300

[OK] idx=26 | model=gemma-3-12b-it | score=0.600

[OK] idx=26 | model=gemma-3-27b-it | score=0.600

[OK] idx=26 | model=llama-3.3-70B-Instruct | score=0.600

[OK] idx=26 | model=DeepSeek-R1-Distill-Llama-70B | score=0.300

[OK] idx=26 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.200

[OK] idx=26 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.500

[OK] idx=26 | model=qwen/qwen3-30b-a3b-2507 | score=0.400

[OK] idx=26 | model=meta-llama-3.1-8B-Instruct | score=0.200

[OK] idx=26 | model=llama-3.2-1B-Instruct | score=0.100

[OK] idx=26 | model=llama-3.2-3B-Instruct | score=0.200

[OK] idx=26 | model=DeepSeek-R1-Distill-Llama-8B | score=0.200

[OK] idx=26 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=26 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=26 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.300

[OK] idx=26 | model=Phi-4-mini-instruct | score=0.500

[OK] idx=26 | model=qwen/qwen3-4b-2507 | score=0.200

[OK] idx=26 | model=gpt-oss-120b | score=0.400

[OK] idx=26 | model=gpt-oss-20b | score=0.700

[OK] idx=27 | model=gemma-3-4b-it | score=0.000

[OK] idx=27 | model=gemma-3-12b-it | score=0.300

[OK] idx=27 | model=gemma-3-27b-it | score=0.300

[OK] idx=27 | model=llama-3.3-70B-Instruct | score=0.300

[OK] idx=27 | model=DeepSeek-R1-Distill-Llama-70B | score=0.300

[OK] idx=27 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.200

[OK] idx=27 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.100

[OK] idx=27 | model=qwen/qwen3-30b-a3b-2507 | score=0.600

[OK] idx=27 | model=meta-llama-3.1-8B-Instruct | score=0.200

[OK] idx=27 | model=llama-3.2-1B-Instruct | score=0.100

[OK] idx=27 | model=llama-3.2-3B-Instruct | score=0.300

[OK] idx=27 | model=DeepSeek-R1-Distill-Llama-8B | score=0.300

[OK] idx=27 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=27 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=27 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.200

[OK] idx=27 | model=Phi-4-mini-instruct | score=0.000

[OK] idx=27 | model=qwen/qwen3-4b-2507 | score=0.200

[OK] idx=27 | model=gpt-oss-120b | score=0.600

[OK] idx=27 | model=gpt-oss-20b | score=0.700

[OK] idx=28 | model=gemma-3-4b-it | score=0.300

[OK] idx=28 | model=gemma-3-12b-it | score=0.400

[OK] idx=28 | model=gemma-3-27b-it | score=0.400

[OK] idx=28 | model=llama-3.3-70B-Instruct | score=0.400

[OK] idx=28 | model=DeepSeek-R1-Distill-Llama-70B | score=0.300

[OK] idx=28 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.300

[OK] idx=28 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.600

[OK] idx=28 | model=qwen/qwen3-30b-a3b-2507 | score=0.400

[OK] idx=28 | model=meta-llama-3.1-8B-Instruct | score=0.200

[OK] idx=28 | model=llama-3.2-1B-Instruct | score=0.200

[OK] idx=28 | model=llama-3.2-3B-Instruct | score=0.400

[OK] idx=28 | model=DeepSeek-R1-Distill-Llama-8B | score=0.200

[OK] idx=28 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=28 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=28 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.300

[OK] idx=28 | model=Phi-4-mini-instruct | score=0.200

[OK] idx=28 | model=qwen/qwen3-4b-2507 | score=0.300

[OK] idx=28 | model=gpt-oss-120b | score=0.800
[SKIP] idx=28 | model=gpt-oss-20b → inferência vazia

[OK] idx=29 | model=gemma-3-4b-it | score=0.300

[OK] idx=29 | model=gemma-3-12b-it | score=0.500

[OK] idx=29 | model=gemma-3-27b-it | score=0.700

[OK] idx=29 | model=llama-3.3-70B-Instruct | score=0.600

[OK] idx=29 | model=DeepSeek-R1-Distill-Llama-70B | score=0.300

[OK] idx=29 | model=DeepSeek-R1-Distill-Qwen-32B | score=0.300

[OK] idx=29 | model=mistral-small-3.2-24B-Instruct-2506 | score=0.600

[OK] idx=29 | model=qwen/qwen3-30b-a3b-2507 | score=0.800

[OK] idx=29 | model=meta-llama-3.1-8B-Instruct | score=0.700

[OK] idx=29 | model=llama-3.2-1B-Instruct | score=0.000

[OK] idx=29 | model=llama-3.2-3B-Instruct | score=0.300

[OK] idx=29 | model=DeepSeek-R1-Distill-Llama-8B | score=0.300

[OK] idx=29 | model=DeepSeek-R1-Distill-Qwen-1.5B | score=0.000

[OK] idx=29 | model=DeepSeek-R1-Distill-Qwen-7B | score=0.000

[OK] idx=29 | model=DeepSeek-R1-Distill-Qwen-14B | score=0.400

[OK] idx=29 | model=Phi-4-mini-instruct | score=0.400

[OK] idx=29 | model=qwen/qwen3-4b-2507 | score=0.700

[OK] idx=29 | model=gpt-oss-120b | score=0.800

[OK] idx=29 | model=gpt-oss-20b | score=0.600

✅ Avaliação concluída! Resultados salvos em 'geval_results_gpt.csv'